# https://arxiv.org/abs/1811.11819

gpu_ids: '0'

model:
  embedding: "Conv64F1600"  # Conv64F1600 / Conv64F
  classifier: "ProtoNet"  # protonet / SVM_CS / DN4
  kwargs: "{}"

datasets:
  root: "/data/tiexin/DataSets/miniImageNet"
  train_data_dir: "../datasets/miniImageNet/train.csv"
  val_data_dir: "../datasets/miniImageNet/val.csv"
  test_data_dir: "../datasets/miniImageNet/test.csv"
  episode_train_num: 10000  # 10000
  episode_val_num: 1000
  episode_test_num: 1000
  name: "miniImageNet"
  nclass: 100
  way_num: 5
  shot_num: 1
  query_num: 15

dataloader:
  train_batch_size: 16 # 128
  test_batch_size: 8
  image_size: 84
  num_workers: 8
  shuffle: True

trainer:
  loggers: ['console', 'file']
  eval_in_training: True
  no_augment: False # False

  eps: 0.0  # label smooth [no label smooth : eps<=0.]
  output_dir: "../saved_model/ULDA_exp"
  seed: 12345
  epochs: 60
  test_epoch: -1
  stage: 'test'
  save_freq: 5
  print_freq: 50

scheduler:
  name: 'lambda'
  warmup_epochs: 0
  iteration_decay: False
  kwargs : "{'step_size':10, 'gamma':0.1}"

solver:
  base_lr: 0.001   # 0.1
  optimizer: "SGD"
  momentum: 0.9
  weight_decay: 5e-4
  criterion: 'cross_entropy'
